checkpoints:
  checkpoint: juggernaut_final.safetensors
  comfy_extra_model_folder: C:/Users/davey/Software/stable-stuff/stable-diffusion-webui/models/Stable-diffusion
  comfy_model_folder: D:/LLaMA/ComfyUI_windows_portable/ComfyUI/models
  external_vae: vae-ft-mse-840000-ema-pruned.ckpt
  sdxl_refiner: animagine-xl.safetensors
  upscale_model: 2xLexicaSwinIR.pth
  use_ex_vae: true
lora:
  clip_strength: 1.0
  lora_file: DetailedEyes_xl_V2.safetensors
  model_strength: 1.0
  use: false
parameters:
  batch_size: 1
  cfg: 8
  height: 512
  iterations: 1
  model_upscale: false
  sampler: dpmpp_2m
  scheduler: karras
  sdxl_refiner: false
  sdxl_refiner_steps: 5
  seed: -1
  steps: 20
  width: 576
preferences:
  keep_images: false
  max_images: 32
