checkpoints:
  comfy_model_folder: 
  comfy_extra_model_folder: 
  sd12: 
  sd12_vae: 
  sdxl_base: 
  sdxl_refiner: 
  sdxl_vae: 
  upscale_model: 
  use_ex_vae: false
lora:
  clip_strength: 1.0
  model_strength: 1.0
  sd12: 
  sdxl: 
  use: false
parameters:
  batch_size: 1
  cfg: 8
  height: 1024
  hrf_check: false
  hrf_scaleby: 1.4
  hrf_steps: 12
  iterations: 1
  mode: SDXL
  model_upscale: false
  sampler: dpmpp_2m
  scheduler: karras
  sdxl_refiner: false
  sdxl_refiner_steps: 5
  seed: -1
  steps: 20
  width: 1024