checkpoints:
  checkpoint: 
  comfy_extra_model_folder: 
  comfy_model_folder: 
  external_vae: 
  sdxl_refiner: 
  upscale_model: 
  use_ex_vae: false
lora:
  clip_strength: 1.0
  lora_file: 
  model_strength: 1.0
  use: false
parameters:
  batch_size: 1
  cfg: 8
  height: 1024
  iterations: 1
  model_upscale: false
  sampler: dpmpp_2m
  scheduler: karras
  sdxl_refiner: false
  sdxl_refiner_steps: 5
  seed: -1
  steps: 20
  width: 1024
preferences:
  keep_images: false
  max_images: 32